// <auto-generated />
using DjHaag.Persitence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DjHaag.Persitence.Migrations
{
    [DbContext(typeof(DjHaagDbContext))]
    [Migration("20220809094447_AddCompetenceMatricesTables")]
    partial class AddCompetenceMatricesTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DjHaag.Persitence.CategoryTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompetenceMatriceId")
                        .HasColumnType("int");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompetenceMatriceId");

                    b.ToTable("CategoryThemes");
                });

            modelBuilder.Entity("DjHaag.Persitence.CompetenceMatrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompetenceMatricesCategory")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CompetenceMatrices");
                });

            modelBuilder.Entity("DjHaag.Persitence.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("DjHaag.Persitence.CategoryTheme", b =>
                {
                    b.HasOne("DjHaag.Persitence.CompetenceMatrice", "CompetenceMatrice")
                        .WithMany("CategoryThemes")
                        .HasForeignKey("CompetenceMatriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetenceMatrice");
                });

            modelBuilder.Entity("DjHaag.Persitence.CompetenceMatrice", b =>
                {
                    b.Navigation("CategoryThemes");
                });
#pragma warning restore 612, 618
        }
    }
}
